#!/bin/sh
export USER=${POSTGRES_USER:-${DATABASE_USERNAME}}
export PASSWORD=$(printf %s "${POSTGRES_PASSWORD:-$(cat "${DATABASE_PASSWORD_FILENAME}")}")
export DATABASE=${POSTGRES_DB:-${DATABASE_NAME}}
psql --username $USER --dbname postgres <<-EOSQL
  CREATE DATABASE $DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $DATABASE TO $USER;
EOSQL
