"""Add worker migrations

Revision ID: 057834a5297b
Revises: e9c082ee8c26
Create Date: 2021-05-25 15:40:22.523269+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "057834a5297b"
down_revision = "e9c082ee8c26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("sent", sa.Boolean(), nullable=True))
    op.add_column(
        "tasks",
        sa.Column(
            "timeliness",
            sa.Enum("unknown", "on_time", "late", "very_late", name="tasktimeliness"),
            nullable=True,
        ),
    )
    op.add_column("workers", sa.Column("task_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, "workers", "tasks", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workers", type_="foreignkey")
    op.drop_column("workers", "task_id")
    op.drop_column("tasks", "timeliness")
    op.drop_column("tasks", "sent")
    # ### end Alembic commands ###
