"""Change timeliness type name

Revision ID: 910b705fa1b9
Revises: 437b455ea3d6
Create Date: 2021-05-29 21:42:54.172592+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "910b705fa1b9"
down_revision = "437b455ea3d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tasktimeliness RENAME TO task_timeliness")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE task_timeliness RENAME TO tasktimeliness")
    # ### end Alembic commands ###
